### PR TITLE
Handle anonymous inner classes

### LINKED ISSUE #173: Unexpected error for anonymous class that extends nested class
For the following case, 

```
import org.checkerframework.checker.regex.qual.Regex;

public class Nested {

    OuterI.@Regex InnerI f = new OuterI.@Regex InnerI() {};
}

class OuterI {
    static class InnerI {}
}
```

the error message is 
```
case/Nested.java:5: error: [assignment.type.incompatible] incompatible types in assignment.
    OuterI.@Regex InnerI f = new OuterI.@Regex InnerI() {};
                             ^
  found   : Nested.<anonymous Nested$1>
  required: @Regex InnerI
1 error
```

The expected output should be a warning of `[cast.unsafe.constructor.invocation]`, i.e. " constructor invocation cast from "@UnknownRegex" to "@Regex" cannot be statically verified."

### PR DESCRIPTION
**Pull request by d367wang**
Fixes #173

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 1]
```diff
@@ -2376,6 +2378,22 @@ public AnnotatedDeclaredType fromNewClass(NewClassTree newClassTree) {
...
                     newClassTree.getClassBody().getModifiers().getAnnotations();
+
+            // This is to handle special cases of form `new OuterI.@XXX InnerI(){}`. Due to the
+            // compiler's flaw, the explicit annotation on the inner identifier is not copied to the
+            // anonymous class as expected. Instead it appears on the `extends/implements` clause.
+            // Therefore we manually copy it to annotate the anonymous class.
+            if (annos.isEmpty()) {
+                Tree node = newClassTree.getIdentifier();
+                if (node instanceof ParameterizedTypeTree) {
+                    node = ((ParameterizedTypeTree) newClassTree.getIdentifier()).getType();
```
Comment (d367wang) [inline framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java:2389]: node = node.getType();

File: framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 2]
```diff
@@ -2376,6 +2378,23 @@ public AnnotatedDeclaredType fromNewClass(NewClassTree newClassTree) {
             // are on not on the identifier newClassTree, but rather on the modifier newClassTree.
             List<? extends AnnotationTree> annos =
                     newClassTree.getClassBody().getModifiers().getAnnotations();
+
+            // If newClassTree creates an anonymous class from an inner class or inner interface,
+            // then annotations in this location:
+            //   new OuterI.@HERE InnerI(){}
+            // are on not on the anonymous class modifier, but rather on the type identifier as well
```
Comment (d367wang) [inline framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java:2385]: are not on

**Review by wmdietl — APPROVED** [review]
Thanks!
